#!/usr/bin/env ruby
# frozen_string_literal: true

# Structural validation of every formula in the tap. Deliberately not `brew style` or
# `brew audit`: the formulae here are generated by GoReleaser and trip their opinions
# (empty `desc`, Sorbet sigils, no `test do` block), so those tools cannot gate this
# repository without blocking every release bump.

require "pathname"

formulae = Dir.glob("*.rb").sort
failures = []

formulae.each do |file|
  source = File.read(file)

  begin
    RubyVM::InstructionSequence.compile(source, file)
  rescue SyntaxError => e
    failures << "#{file}: syntax error: #{e.message.lines.first.strip}"
    next
  end

  # Homebrew derives the class name from the file name; a mismatch makes the formula
  # unreachable rather than broken, so nothing else catches it.
  expected = Pathname.new(file).basename(".rb").to_s.split("-").map(&:capitalize).join
  unless source.match?(/^class #{Regexp.escape(expected)} < Formula\b/)
    failures << "#{file}: expected 'class #{expected} < Formula'"
  end

  urls = source.scan(/^\s*url\s+"/).length
  sha256s = source.scan(/^\s*sha256\s+"/).length
  unless urls == sha256s
    failures << "#{file}: #{urls} url(s) but #{sha256s} sha256(s)"
  end
end

if failures.empty?
  puts "ok: #{formulae.length} formulae"
else
  failures.each { |failure| puts "FAIL #{failure}" }
  exit 1
end
