# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DummyBlockchain < Formula
  desc ""
  homepage "https://github.com/streamingfast/dummy-blockchain"
  version "1.7.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.8/dummy-blockchain_darwin_x86_64.tar.gz"
      sha256 "fe866b95718af154eaace8bbcd2dd6a635053647daa6ff0a2f058cbe065e9e72"

      define_method(:install) do
        bin.install "dummy-blockchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.8/dummy-blockchain_darwin_arm64.tar.gz"
      sha256 "b59597a47ec9225fb54583ed381349264b57dc8948094d001e1f7fd82e2bc22f"

      define_method(:install) do
        bin.install "dummy-blockchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.8/dummy-blockchain_linux_x86_64.tar.gz"
      sha256 "ba3a5c83bae8cfec19ee29234e9582068f2da99ff161578f1323e3c5007db1f2"
      define_method(:install) do
        bin.install "dummy-blockchain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.8/dummy-blockchain_linux_arm64.tar.gz"
      sha256 "4aa328ba915ad3e547f34fa18afb4b24efa6a03a421a95934ed23f622756ffc3"
      define_method(:install) do
        bin.install "dummy-blockchain"
      end
    end
  end
end
