# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DummyBlockchain < Formula
  desc ""
  homepage "https://github.com/streamingfast/dummy-blockchain"
  version "1.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.1/dummy-blockchain_darwin_x86_64.tar.gz"
      sha256 "845e8c4e38ceb1414406b9c65133ad7bef1970fe27b3f40c64633baf78f2c0a4"

      def install
        bin.install "dummy-blockchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.1/dummy-blockchain_darwin_arm64.tar.gz"
      sha256 "2e32e7c5923d42e418a0b67209e20490d97daeee8ac68d203a4f6ee0b4d125e7"

      def install
        bin.install "dummy-blockchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.1/dummy-blockchain_linux_x86_64.tar.gz"
      sha256 "2e0ef6a5a1124e4957630341b32b57db1b000752ac860f333e62c507a7f3092a"
      def install
        bin.install "dummy-blockchain"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/dummy-blockchain/releases/download/v1.7.1/dummy-blockchain_linux_arm64.tar.gz"
      sha256 "520a2c2e23daea547109c167e5ebe3c95a4003df99f9e17d0f178b6d7437316c"
      def install
        bin.install "dummy-blockchain"
      end
    end
  end
end
