# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseEthereum < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-ethereum"
  version "2.14.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-ethereum/releases/download/v2.14.2/firehose-ethereum_darwin_x86_64.tar.gz"
      sha256 "9841a5cb82fec33aa3647e2f0424c06f2f38558a2bf9a460d453caadc9a3b324"

      def install
        bin.install "fireeth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-ethereum/releases/download/v2.14.2/firehose-ethereum_darwin_arm64.tar.gz"
      sha256 "d912be7a9c43421fc7e78579ef073371e830db9e78ea55429fbab531e7722a98"

      def install
        bin.install "fireeth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-ethereum/releases/download/v2.14.2/firehose-ethereum_linux_x86_64.tar.gz"
      sha256 "2e7bbb97d5440c7963e5b559de2d72ca5cb81b0b3d3339ccba0051d008042cea"
      def install
        bin.install "fireeth"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-ethereum/releases/download/v2.14.2/firehose-ethereum_linux_arm64.tar.gz"
      sha256 "cd8602a6f8d16c71879e7cb856a734e99b1242364fa221070e7384fb27e9c74b"
      def install
        bin.install "fireeth"
      end
    end
  end
end
