# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseBitcoin < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-bitcoin"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0/firehose-bitcoin_darwin_arm64.tar.gz"
      sha256 "e00d7af2eee1405e79d8efd4ff33c5c189995fb7a6eabb93d4bc84309bf0b43e"

      def install
        bin.install "firebtc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0/firehose-bitcoin_darwin_x86_64.tar.gz"
      sha256 "9ccbaa14b11a1cec61c3c38e9339d304ea1e091c183550abbf3a9862fd48008b"

      def install
        bin.install "firebtc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0/firehose-bitcoin_linux_arm64.tar.gz"
      sha256 "56f0737799538d0b020b483c8505389f2091cbd6427acfa463e94ba7a99498e7"

      def install
        bin.install "firebtc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0/firehose-bitcoin_linux_x86_64.tar.gz"
      sha256 "0ff8a0106b06f8e24b1e5831d334a9a94b1f2224e3003017dc6eb98f408b1707"

      def install
        bin.install "firebtc"
      end
    end
  end
end
