# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseSolana < Formula
  desc "StreamingFast CLI for 'firehose-solana'"
  homepage "https://github.com/streamingfast/firehose-solana"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v0.2.0/firehose-solana_darwin_arm64.tar.gz"
      sha256 "e438e2fd256d3764eb11a16a065f86a2213e22a3aee175cc8a006d3a49b9515d"

      def install
        bin.install "firesol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v0.2.0/firehose-solana_darwin_x86_64.tar.gz"
      sha256 "819c9d08fc6ff07fe95f1328c13fda050959260df8dfd8cd7c78b7e21e9655bf"

      def install
        bin.install "firesol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v0.2.0/firehose-solana_linux_x86_64.tar.gz"
      sha256 "32facdca06a07e03b0599f1b9f583fd244c47b6638ff3d1792efc64e37dab7fe"

      def install
        bin.install "firesol"
      end
    end
  end
end
