# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseCore < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-core"
  version "1.5.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-core/releases/download/v1.5.2/firehose-core_darwin_arm64.tar.gz"
      sha256 "9ad20bc20cd03a82e3db92db77b30083bec7bc6da261a7326a824ba15a0c261e"

      def install
        bin.install "firecore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-core/releases/download/v1.5.2/firehose-core_darwin_x86_64.tar.gz"
      sha256 "6f688fd135e0356e07835c2facbfe5a7cb6e8c2b7c66d9167d276c36d8fee800"

      def install
        bin.install "firecore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-core/releases/download/v1.5.2/firehose-core_linux_arm64.tar.gz"
      sha256 "cd1bf8026e63df9d99189e922ebc6c6a23aa5ab23abac6bff2696ac099364cc0"

      def install
        bin.install "firecore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-core/releases/download/v1.5.2/firehose-core_linux_x86_64.tar.gz"
      sha256 "c3b538e9bd8728b68ba10be1cb0a881340af708051b54feeceb4acf7a3f10f28"

      def install
        bin.install "firecore"
      end
    end
  end
end
