# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseAcme < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-acme"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-acme/releases/download/v0.1.0/firehose-acme_darwin_arm64.tar.gz"
      sha256 "0b95f627f3b2553c7f067ba23a85abcd7d6b0f39e2a7cb5af043c139de0ae633"

      def install
        bin.install "fireacme"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-acme/releases/download/v0.1.0/firehose-acme_darwin_x86_64.tar.gz"
      sha256 "6784934821a544020726122ee3ec66f4c44366f3c8ed5efb4ecb74e492f2f823"

      def install
        bin.install "fireacme"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-acme/releases/download/v0.1.0/firehose-acme_linux_x86_64.tar.gz"
      sha256 "de129ee3a6f0a571e5b2ce9f4eb6c1661f006b32fcaf4daa4b918d09d849173c"

      def install
        bin.install "fireacme"
      end
    end
  end
end
