# typed: false
# frozen_string_literal: true

# Generated by streamingfast/firehose-tron .github/workflows/release.yml on tag push. DO NOT EDIT.
class FirehoseTron < Formula
  desc "Firehose and Substreams support for the Tron blockchain"
  homepage "https://github.com/streamingfast/firehose-tron"
  version "0.5.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.2/firehose-tron_darwin_x86_64.tar.gz"
      sha256 "4b8092076e2150550c89260ec9ca0479537969c3f1823f2f84e3edc0223ae4e1"

      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.2/firehose-tron_darwin_arm64.tar.gz"
      sha256 "4af7853349f15a3dce96b3092ac28ef1eb2cdad9c2a81a43bbeffdc6e5cf908b"

      define_method(:install) do
        bin.install "firetron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.2/firehose-tron_linux_x86_64.tar.gz"
      sha256 "5f47c5183ee9a9a374d8e900e43013037bb7d02fcb5d87e148f47ed72db8ee1a"
      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.2/firehose-tron_linux_arm64.tar.gz"
      sha256 "4e310dbfa27b57a5fc79b5fbd002ae129883cd8ed8c5e0c76a529747976e4ec4"
      define_method(:install) do
        bin.install "firetron"
      end
    end
  end
end
