# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseSolana < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-solana"
  version "1.1.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.1.4/firehose-solana_darwin_x86_64.tar.gz"
      sha256 "ec2ecedac2a5dadab633c06a0f97d196d80aa3958686f2c8fe91f7ed3d59e7d2"

      def install
        bin.install "firesol"
      end
    end
    on_arm do
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.1.4/firehose-solana_darwin_arm64.tar.gz"
      sha256 "cbe3a8668fe86c962fda270b53fa3d2bb9d0d7b269cbfbb40d5651592bc16c06"

      def install
        bin.install "firesol"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/firehose-solana/releases/download/v1.1.4/firehose-solana_linux_x86_64.tar.gz"
        sha256 "227c7a99a29c0b747f21071bd6c5cb7cca70e11ab691e7127432a6a667cebfe2"

        def install
          bin.install "firesol"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/firehose-solana/releases/download/v1.1.4/firehose-solana_linux_arm64.tar.gz"
        sha256 "d1f142fcf21a718b9a6f24455eeb134e22f4701793aab4fad75df7ffe8a37bdd"

        def install
          bin.install "firesol"
        end
      end
    end
  end
end
