# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseSolana < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-solana"
  version "1.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.0.3/firehose-solana_darwin_arm64.tar.gz"
      sha256 "91849f8de6f9e433fe558f81511f5a5a9de8b3334d98cbf05c92394dea3b3122"

      def install
        bin.install "firesol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.0.3/firehose-solana_darwin_x86_64.tar.gz"
      sha256 "aaf8bf482879721b08df0f5760ca4eb3676e71646e0f4d71e65991010213461c"

      def install
        bin.install "firesol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.0.3/firehose-solana_linux_arm64.tar.gz"
      sha256 "855783c7a6c62a414251b3ca7e22391434e0b39de63ecb95c9221e3f67e10d17"

      def install
        bin.install "firesol"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-solana/releases/download/v1.0.3/firehose-solana_linux_x86_64.tar.gz"
      sha256 "49fa15490752785c716e287a2e77537bf851d990b585023e3e3d79daa267ff93"

      def install
        bin.install "firesol"
      end
    end
  end
end
