# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseStellar < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-stellar"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-stellar/releases/download/v1.0.2/firehose-stellar_darwin_x86_64.tar.gz"
      sha256 "48a760b3b9ea67cbcdcba6b9193c7b0bd9802d1d1d7292daf7d7a72573229bce"

      def install
        bin.install "firestellar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-stellar/releases/download/v1.0.2/firehose-stellar_darwin_arm64.tar.gz"
      sha256 "4c905609d06fbf6234efa0a0616e141645f910c52cd8fcd350d4d7198a5abb21"

      def install
        bin.install "firestellar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-stellar/releases/download/v1.0.2/firehose-stellar_linux_x86_64.tar.gz"
      sha256 "650ab2011454e31feb6914d5c40dc1233b6837a2f04d3dc0afbfe7fb799084c9"
      def install
        bin.install "firestellar"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-stellar/releases/download/v1.0.2/firehose-stellar_linux_arm64.tar.gz"
      sha256 "9290d29309e1de901cef10c79fe6f1bcd94cd084b731b655c136acee3c2b4efd"
      def install
        bin.install "firestellar"
      end
    end
  end
end
