# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseBitcoin < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-bitcoin"
  version "1.0.0-rc.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0-rc.1/firehose-bitcoin_darwin_arm64.tar.gz"
      sha256 "3c0d0b269be7d1c2837493fb871f3bbda276ef36a160d8797789056aa84a68bc"

      def install
        bin.install "firebtc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0-rc.1/firehose-bitcoin_darwin_x86_64.tar.gz"
      sha256 "acceb2f1f485e8c40f5148a85bdd592de6378a513c03c296a010007d81c31bb8"

      def install
        bin.install "firebtc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0-rc.1/firehose-bitcoin_linux_arm64.tar.gz"
      sha256 "f43cf107be0ece4eb12d678dc0508b0ac82349e6550686466f6b854dbe6197ce"

      def install
        bin.install "firebtc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-bitcoin/releases/download/v1.0.0-rc.1/firehose-bitcoin_linux_x86_64.tar.gz"
      sha256 "f799eb2948277528974a99d4d89edaa97dd7fac605f2a896372cfbf7883df4e3"

      def install
        bin.install "firebtc"
      end
    end
  end
end
