# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseStarknet < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-starknet"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v0.2.0/firehose-starknet_darwin_x86_64.tar.gz"
      sha256 "e50178ed5c933febba99d14cbcd067a0273770452cd80b94fe10503ae89bfd07"

      def install
        bin.install "firestarknet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v0.2.0/firehose-starknet_darwin_arm64.tar.gz"
      sha256 "8f31244ef931f488d47a25865a58d1b02b71284922788add5ad32bcb6fcdfefc"

      def install
        bin.install "firestarknet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/firehose-starknet/releases/download/v0.2.0/firehose-starknet_linux_x86_64.tar.gz"
        sha256 "d7b04f254b9b7f18f692ffcebe99bf0832ce837bec38802a86ce2525bc43aff9"

        def install
          bin.install "firestarknet"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/firehose-starknet/releases/download/v0.2.0/firehose-starknet_linux_arm64.tar.gz"
        sha256 "7fc0d7466361e58ce372dc02563f96fa64fca1eb3f19ddfdd70c7699425a1785"

        def install
          bin.install "firestarknet"
        end
      end
    end
  end
end
