# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseStarknet < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-starknet"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v1.1.2/firehose-starknet_darwin_x86_64.tar.gz"
      sha256 "f9ea3165e681717e52d14b1f8dfdeb89f67189e01838ca825d7a223f35c08498"

      def install
        bin.install "firestarknet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v1.1.2/firehose-starknet_darwin_arm64.tar.gz"
      sha256 "ef60c5d5203fcddde212fb6e0106b68c36f23a801de8f0febd008b2d59b5172d"

      def install
        bin.install "firestarknet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v1.1.2/firehose-starknet_linux_x86_64.tar.gz"
      sha256 "832748d35bc7edba656093b4f8f5c4d913d04a22e3fd4253b4ea6ed80fcbc10e"
      def install
        bin.install "firestarknet"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-starknet/releases/download/v1.1.2/firehose-starknet_linux_arm64.tar.gz"
      sha256 "48e1ba2ee8709c83daaeb1d07364db3f4529593f35533e435e4b285f0fa43baf"
      def install
        bin.install "firestarknet"
      end
    end
  end
end
