# typed: false
# frozen_string_literal: true

# Generated by streamingfast/firehose-tron .github/workflows/release.yml on tag push. DO NOT EDIT.
class FirehoseTron < Formula
  desc "Firehose and Substreams support for the Tron blockchain"
  homepage "https://github.com/streamingfast/firehose-tron"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.0/firehose-tron_darwin_x86_64.tar.gz"
      sha256 "75f0f0771d357363e1d58f4d2bdcdfda98e5958bc40a9ab883231cf0533d7b3f"

      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.0/firehose-tron_darwin_arm64.tar.gz"
      sha256 "f7bf5768b859e7819f3cf5a3481dece02fa5bc9a19ef9958a0d94d7f5525432b"

      define_method(:install) do
        bin.install "firetron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.0/firehose-tron_linux_x86_64.tar.gz"
      sha256 "9c9f9001ad83feccc092c52035c8cfc12936855a46b2861be6130c48041fb07f"
      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.5.0/firehose-tron_linux_arm64.tar.gz"
      sha256 "e457e762e211a7b4df233186b7c765b8b5a2d39a72fc3939a11d83f7a58bf28f"
      define_method(:install) do
        bin.install "firetron"
      end
    end
  end
end
