# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirehoseTron < Formula
  desc ""
  homepage "https://github.com/streamingfast/firehose-tron"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.2.0/firehose-tron_darwin_x86_64.tar.gz"
      sha256 "2e263478e74e43346e1297122986667b9636f8c4fc71604620138fae3e098dca"

      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.2.0/firehose-tron_darwin_arm64.tar.gz"
      sha256 "dbec492dc2986e4efd1750a7fa96dadf5b266367239275f573d96bc6bd069ac9"

      define_method(:install) do
        bin.install "firetron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.2.0/firehose-tron_linux_x86_64.tar.gz"
      sha256 "75195a3341af52f2ebbaab138676dff1b32b9b55571570fdd09ea01952daa8ae"
      define_method(:install) do
        bin.install "firetron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/firehose-tron/releases/download/v0.2.0/firehose-tron_linux_arm64.tar.gz"
      sha256 "b4ab35b0f27d64358ab4684562bc463f5e844ba5d9934d6f53fb97dcae16c7cb"
      define_method(:install) do
        bin.install "firetron"
      end
    end
  end
end
