# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbox < Formula
  desc ""
  homepage "https://github.com/streamingfast/sbox"
  version "1.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sbox/releases/download/v1.9.0/sbox_darwin_x86_64.tar.gz"
      sha256 "0c4a4aeb8f62f1c04e1353cb12510dcb0677fb17214ec0ea6112ea7760c44351"

      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sbox/releases/download/v1.9.0/sbox_darwin_arm64.tar.gz"
      sha256 "d00fe36c06786125cea40e485842e46df7d24d4662ffd27822b3ad0cfbbfe036"

      def install
        bin.install "sbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.9.0/sbox_linux_x86_64.tar.gz"
      sha256 "16a8abcb4ed771550acb5c32884c9d765494d1e6abe80b3c48915a0a17829da7"
      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.9.0/sbox_linux_arm64.tar.gz"
      sha256 "56687563d8c717a229f7f11ae763ae173f28d698c36d366376ce523f5990645f"
      def install
        bin.install "sbox"
      end
    end
  end
end
