# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbox < Formula
  desc ""
  homepage "https://github.com/streamingfast/sbox"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sbox/releases/download/v1.0.0/sbox_darwin_x86_64.tar.gz"
      sha256 "e3651c271fda0b9e5662eb857c1a48ba76f02d6229bbc000f3c77a550d826ac9"

      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sbox/releases/download/v1.0.0/sbox_darwin_arm64.tar.gz"
      sha256 "3ef2fe81e59ef550a80538634728cdabe83f15b9575bd884fec9fe6b37fb9094"

      def install
        bin.install "sbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.0.0/sbox_linux_x86_64.tar.gz"
      sha256 "4c4ffebe6d4922911568f4ef16e1bcbce8516c66ec189aaaf633202b856b2c2d"
      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.0.0/sbox_linux_arm64.tar.gz"
      sha256 "cf901999cc2623f977cb7aad19ba746ee0fd90319ac93713553c6fbf3afe7f04"
      def install
        bin.install "sbox"
      end
    end
  end
end
