# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbox < Formula
  desc ""
  homepage "https://github.com/streamingfast/sbox"
  version "1.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sbox/releases/download/v1.5.1/sbox_darwin_x86_64.tar.gz"
      sha256 "7313f0c22d5c3bf883f48ef5366c9947c57c4af2162693de6bdba3e0e7a74b64"

      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sbox/releases/download/v1.5.1/sbox_darwin_arm64.tar.gz"
      sha256 "7620d60705b928c703b44ebd77219fc7932224903990de87d36e24c2d5335bb3"

      def install
        bin.install "sbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.5.1/sbox_linux_x86_64.tar.gz"
      sha256 "bc80eecb52a7b15980125661d200d9515d81762fea7ec3bd2ca1440725c2049e"
      def install
        bin.install "sbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/sbox/releases/download/v1.5.1/sbox_linux_arm64.tar.gz"
      sha256 "0619708581a0578f616ea0751424a705aaf7767231f0704f69e670d060a3e2c4"
      def install
        bin.install "sbox"
      end
    end
  end
end
