# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SfEthereum < Formula
  desc "Firehose on Ethereum stack"
  homepage "https://github.com/streamingfast/sf-ethereum"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0/sf-ethereum_0.10.0_macOS_arm64.tar.gz"
      sha256 "2e7d3a87e0a7c4b541cac75725a1bacd40213f56ad663e16b3ad2bf747b5fd26"

      def install
        bin.install "sfeth"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0/sf-ethereum_0.10.0_macOS_x86_64.tar.gz"
      sha256 "1a3724a335fa027fff3386f479e1f69ab6a36035901eef8424f5a8eaa79cabdf"

      def install
        bin.install "sfeth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0/sf-ethereum_0.10.0_linux_x86_64.tar.gz"
      sha256 "51e65699e856b724e19e2f0fd0b3ddaaa25bd29d550a21622faaebd4e1668b86"

      def install
        bin.install "sfeth"
      end
    end
  end
end
