# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SfEthereum < Formula
  desc "Firehose on Ethereum stack"
  homepage "https://github.com/streamingfast/sf-ethereum"
  version "0.10.0-rc.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0-rc.4/sf-ethereum_0.10.0-rc.4_macOS_x86_64.tar.gz"
      sha256 "e04cbafe956cfede2b33f69cd847907030f304ce656c49e33e7aeef38fc7902c"

      def install
        bin.install "sfeth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0-rc.4/sf-ethereum_0.10.0-rc.4_macOS_arm64.tar.gz"
      sha256 "354eb74f6ef7d91a785729d037039283036d11acf5af21b833d082eaac7872ba"

      def install
        bin.install "sfeth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-ethereum/releases/download/v0.10.0-rc.4/sf-ethereum_0.10.0-rc.4_linux_x86_64.tar.gz"
      sha256 "aede97646a807ae23873c547da3e2bae926e90604da8ec2a8ce6c1f056422131"

      def install
        bin.install "sfeth"
      end
    end
  end
end
