# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SfNear < Formula
  desc "Firehose on NEAR stack"
  homepage "https://github.com/streamingfast/sf-near"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sf-near/releases/download/v0.3.0/sf-near_0.3.0_macOS_arm64.tar.gz"
      sha256 "50db682db6397cf1727d18e55e851916eeb9f78847acf7c1b81a7dca4c75b693"

      def install
        bin.install "sfnear"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-near/releases/download/v0.3.0/sf-near_0.3.0_macOS_x86_64.tar.gz"
      sha256 "014b99fffabfbe023f624667a722a53aca292e288398410ca6720571968896ce"

      def install
        bin.install "sfnear"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sf-near/releases/download/v0.3.0/sf-near_0.3.0_linux_x86_64.tar.gz"
      sha256 "79ff3a530a310e77733b5c61fced81f24d828ebe7fcc5c2397c3e261e10af93b"

      def install
        bin.install "sfnear"
      end
    end
  end
end
