# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sfreleaser < Formula
  desc ""
  homepage "https://github.com/streamingfast/sfreleaser"
  version "0.5.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/sfreleaser/releases/download/v0.5.4/sfreleaser_darwin_arm64.tar.gz"
      sha256 "3fe0dc3ac15a92e4f123f6812a799f875f55718a57364e5b349cc3a671ec216e"

      def install
        bin.install "sfreleaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sfreleaser/releases/download/v0.5.4/sfreleaser_darwin_x86_64.tar.gz"
      sha256 "df632464e8685de998a67c8ca589abca54f7db5cff5d05a08328324b753c27c1"

      def install
        bin.install "sfreleaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/sfreleaser/releases/download/v0.5.4/sfreleaser_linux_x86_64.tar.gz"
      sha256 "e2fb32d1df8703d62df5f631d05fc63dca331214b72cbc2e611ed7f7d8c700d3"

      def install
        bin.install "sfreleaser"
      end
    end
  end
end
