# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slnc < Formula
  desc "A command-line client to Solana clusters - by StreamingFast (streamingfast.io)"
  homepage "https://github.com/streamingfast.io"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/slnc/releases/download/v0.2.0/slnc_0.2.0_macOS_arm64.tar.gz"
      sha256 "b9ee4fb224ec6cdbda5a981aad40dce511a1907615844fc02f115f50ece7fb23"

      def install
        bin.install "slnc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/slnc/releases/download/v0.2.0/slnc_0.2.0_macOS_x86_64.tar.gz"
      sha256 "9176a59da5d3c4597b68106391fa853a40a525c565fa07d2545370aa49d5e3ca"

      def install
        bin.install "slnc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/slnc/releases/download/v0.2.0/slnc_0.2.0_linux_x86_64.tar.gz"
      sha256 "b69d2f24bb79ec8a1fcfc4696d4f3b96144507dd07ec846183bd05e622820146"

      def install
        bin.install "slnc"
      end
    end
  end
end
