# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SolanaGo < Formula
  desc "A command-line client to Solana clusters - by StreamingFast (streamingfast.io)"
  homepage "https://github.com/streamingfast/slnc"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dfuse-io/solana-go/releases/download/v0.2.0/solana-go_0.2.0_macOS_x86_64.tar.gz"
    sha256 "5d007901bf1ac0651965695f5e2d230019acf81fd516ed9d714d2f5c852ea644"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dfuse-io/solana-go/releases/download/v0.2.0/solana-go_0.2.0_linux_x86_64.tar.gz"
      sha256 "a9323f8e7f6e93e63b7c886e3d6d0f6d3425e5529c1efbe7eecf2ff9dcc5190d"
    end
  end

  def install
    bin.install "slnc"
  end
end
