# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StreamingfastComparator < Formula
  desc ""
  homepage "https://github.com/streamingfast/streamingfast-comparator"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/streamingfast-comparator/releases/download/v0.1.0/streamingfast-comparator_darwin_x86_64.tar.gz"
      sha256 "ca24bc49b68e15851f9af902e34cffe78095349ca7749915ae9ea77f631a6cdb"

      def install
        bin.install "streamingfast-comparator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/streamingfast-comparator/releases/download/v0.1.0/streamingfast-comparator_darwin_arm64.tar.gz"
      sha256 "2d5da8c474fd500a2eac3621bdbd5c8d4897b2eb8f18816ba47d5f2728b02721"

      def install
        bin.install "streamingfast-comparator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/streamingfast-comparator/releases/download/v0.1.0/streamingfast-comparator_linux_x86_64.tar.gz"
      sha256 "4eb444d7721415e5d8d297afca5a9c91609301e2df29d4ad63109bea340252fd"
      def install
        bin.install "streamingfast-comparator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/streamingfast-comparator/releases/download/v0.1.0/streamingfast-comparator_linux_arm64.tar.gz"
      sha256 "0a6fa1d8f751e1c267dbe69e9303787537ffdf0752c7687a544f699ba79d0156"
      def install
        bin.install "streamingfast-comparator"
      end
    end
  end
end
