# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Substreams < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams"
  version "1.18.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams/releases/download/v1.18.4/substreams_darwin_x86_64.tar.gz"
      sha256 "5f3b966433aebac4841af609d7cd1d3b95e4266f38d47e906cf57f2440768cd1"

      def install
        bin.install "substreams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams/releases/download/v1.18.4/substreams_darwin_arm64.tar.gz"
      sha256 "1e56be44d4713dc7652ed0684245ffe28f31820827e3c6be93093fbc3edb1a01"

      def install
        bin.install "substreams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams/releases/download/v1.18.4/substreams_linux_x86_64.tar.gz"
      sha256 "fe1f667516e0299b2fa57d9971422592406ada6f89a9257e0f5a99c065cc5a64"
      def install
        bin.install "substreams"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams/releases/download/v1.18.4/substreams_linux_arm64.tar.gz"
      sha256 "346aeacc56a945e9e0630f2f7586da8912157410926e7fc2c34324f9518a3993"
      def install
        bin.install "substreams"
      end
    end
  end
end
