# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkFiles < Formula
  desc "StreamingFast CLI for 'substreams-sink-files'"
  homepage "https://github.com/streamingfast/substreams-sink-files"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v1.0.0/substreams-sink-files_darwin_arm64.tar.gz"
      sha256 "032814fb0f0642fc53da10dad424e58a3809ab3e53dcab57b324cf2767d0e10b"

      def install
        bin.install "substreams-sink-files"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v1.0.0/substreams-sink-files_darwin_x86_64.tar.gz"
      sha256 "777bb59f4e2964c553d7819dc4ca83e6dcd3370318a6ce826aac00b997eeceb9"

      def install
        bin.install "substreams-sink-files"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v1.0.0/substreams-sink-files_linux_x86_64.tar.gz"
      sha256 "2dba073bace80bd4a28dbc7a25c28d887d35b636507620a8bc7d7aa405d8ab19"

      def install
        bin.install "substreams-sink-files"
      end
    end
  end
end
