# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkPostgres < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-postgres"
  version "2.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.2/substreams-sink-postgres_darwin_arm64.tar.gz"
      sha256 "1b833b4d81e8439879b5dfa6e6a4aff653e4d4fe37bae105882207f4a4f2d34a"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.2/substreams-sink-postgres_darwin_x86_64.tar.gz"
      sha256 "02777f278c346024ffc4d9d559509b814b027fe7647fd73423929834b9f58235"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.2/substreams-sink-postgres_linux_x86_64.tar.gz"
      sha256 "e1b0bd2945ed5a48ba50b259910ddc82eab0b6f820fc0ab79b18ba0022232354"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
  end
end
