# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsFoundationalStore < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-foundational-store"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-foundational-store/releases/download/v0.2.3/substreams-foundational-store_darwin_x86_64.tar.gz"
      sha256 "bcd5ebe7c792bd8a4e0f0624a03f4ce2d9e19a9061d515cb2562970536bdfab5"

      define_method(:install) do
        bin.install "foundational-store"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-foundational-store/releases/download/v0.2.3/substreams-foundational-store_darwin_arm64.tar.gz"
      sha256 "d35e2cb7eb036dbbf1fc9000aeed5da16e864da5f856081172045c617f68efc3"

      define_method(:install) do
        bin.install "foundational-store"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-foundational-store/releases/download/v0.2.3/substreams-foundational-store_linux_x86_64.tar.gz"
      sha256 "1c6a021f6091ae3651184ef8534f804e3f8c7aee17e29c4f698cccee931c8e17"
      define_method(:install) do
        bin.install "foundational-store"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-foundational-store/releases/download/v0.2.3/substreams-foundational-store_linux_arm64.tar.gz"
      sha256 "b5a83952d5c30f2f585569b6762194ac7eae8b244a79a569ba92542b7c7784df"
      define_method(:install) do
        bin.install "foundational-store"
      end
    end
  end
end
