# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkSql < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-sql"
  version "4.6.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-sql/releases/download/v4.6.8/substreams-sink-sql_darwin_x86_64.tar.gz"
      sha256 "1600abdbcd843f4ca0e6997fae3b76fcab93ff86d500709c0b636ccbdf7baa2d"

      def install
        bin.install "substreams-sink-sql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-sql/releases/download/v4.6.8/substreams-sink-sql_darwin_arm64.tar.gz"
      sha256 "85797da3c302a24eb907717e56da4c4ccb02cc50deb07db48c38fe5508bae009"

      def install
        bin.install "substreams-sink-sql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-sink-sql/releases/download/v4.6.8/substreams-sink-sql_linux_x86_64.tar.gz"
      sha256 "6190694c375b27340f491a2c615548094a4a177394db75283aaf225d061ea420"
      def install
        bin.install "substreams-sink-sql"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-sink-sql/releases/download/v4.6.8/substreams-sink-sql_linux_arm64.tar.gz"
      sha256 "bfb41b994cc66ae5fea1e004a1f0a67609ff550f6b975600214b6781067642b0"
      def install
        bin.install "substreams-sink-sql"
      end
    end
  end
end
