# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkMongodb < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-mongodb"
  version "2.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.1.0/substreams-sink-mongodb_darwin_x86_64.tar.gz"
      sha256 "3763d1142d4ed137d3c75afaa3a8ce7180853c9a05a5369aebb0fbee2ce98551"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
    on_arm do
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.1.0/substreams-sink-mongodb_darwin_arm64.tar.gz"
      sha256 "c2fa077beeb206a1ba9aebcf32eba6d8028f6dcd3c4a96fb1bb51d5e2c574662"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.1.0/substreams-sink-mongodb_linux_x86_64.tar.gz"
        sha256 "accf9b5c4811242b8ee4bedf150a42512b6c0143ccb40b3840af3442c4c4e99b"

        def install
          bin.install "substreams-sink-mongodb"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.1.0/substreams-sink-mongodb_linux_arm64.tar.gz"
        sha256 "5ae6c17f932f6862713a77fee801984fa9391aff0c9f2b7199908dc83c3a5c21"

        def install
          bin.install "substreams-sink-mongodb"
        end
      end
    end
  end
end
