# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkKv < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-kv"
  version "2.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.5/substreams-sink-kv_darwin_arm64.tar.gz"
      sha256 "8fa6d084d423258a6968aa9f46288e2b0c3d262da48dbd97a9ae7ed56c6ca4f2"

      def install
        bin.install "substreams-sink-kv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.5/substreams-sink-kv_darwin_x86_64.tar.gz"
      sha256 "a4d7f96d860a59a9b3df0ca7e384390909abcb17bb0fcf181443827485993799"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.5/substreams-sink-kv_linux_x86_64.tar.gz"
      sha256 "46e79ce86bd825291b7c555406ec5478a26c217920339f6980f6ed118680ff9f"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end
end
