# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Substreams < Formula
  desc "StreamingFast Substreams CLI"
  homepage "https://github.com/streamingfast/substreams"
  version "0.0.5-beta3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams/releases/download/v0.0.5-beta3/substreams_0.0.5-beta3_macOS_arm64.tar.gz"
      sha256 "fc66b29d52bdb252bd6ffb859530d9aba851c202b3749b34d360257139eedeec"

      def install
        bin.install "substreams"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams/releases/download/v0.0.5-beta3/substreams_0.0.5-beta3_macOS_x86_64.tar.gz"
      sha256 "9c2179db2dece41ffcb393a2d48f474c4b75b49286d43ee01d2e567dea825a77"

      def install
        bin.install "substreams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams/releases/download/v0.0.5-beta3/substreams_0.0.5-beta3_linux_x86_64.tar.gz"
      sha256 "0f72890840b1efc0569c74cbc7306d4ce68c85cc1d8d6ee9c2c39ee778b3ddd0"

      def install
        bin.install "substreams"
      end
    end
  end
end
