# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkMongodb < Formula
  desc "StreamingFast CLI for 'substreams-sink-mongodb'"
  homepage "https://github.com/streamingfast/substreams-sink-mongodb"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.0/substreams-sink-mongodb_darwin_arm64.tar.gz"
      sha256 "1bc9dd3928cea2c73ca4913b09069d0eeb8e483c2ca0cf7a215abf5e1bff0c9a"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.0/substreams-sink-mongodb_darwin_x86_64.tar.gz"
      sha256 "9dacc68d588ed126eee9cd45d0065c43fc1fd49f53dff40534b37d70ec049222"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.0/substreams-sink-mongodb_linux_x86_64.tar.gz"
      sha256 "c03d750ee4f53677a3cc7ee87b7a3adfd69057d6922f297cfb97a5b39f7aecde"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
  end
end
