# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkFiles < Formula
  desc "Substreams Sink tool to extract information to flat files"
  homepage "https://github.com/streamingfast/substreams-sink-files"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v0.1.0/substreams-sink-files_0.1.0_macOS_arm64.tar.gz"
      sha256 "269c2f4baaff2d3dbd60800497ddf6fc8a6a0b35ab0d8b9d760bd6f144698e4f"

      def install
        bin.install "substreams-sink-files"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v0.1.0/substreams-sink-files_0.1.0_macOS_x86_64.tar.gz"
      sha256 "5fec33c8787b2b7dbfbb374bd32b22c558120cbbf31cc413b5bbb20c8030900c"

      def install
        bin.install "substreams-sink-files"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v0.1.0/substreams-sink-files_0.1.0_linux_x86_64.tar.gz"
      sha256 "0ca214d463a06a0c0446b77776a0942e731f7e9ac5ab21630f87f0e0d192fe7e"

      def install
        bin.install "substreams-sink-files"
      end
    end
  end
end
