# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkKv < Formula
  desc "Substreams Sink tool to extract information to a kv store"
  homepage "https://github.com/streamingfast/substreams-sink-kv"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v0.1.1/substreams-sink-kv_0.1.1_macOS_arm64.tar.gz"
      sha256 "2061c9c7a7e251fd274042b449bbc99393fd84de0243a07ee6b6f1989ef5866d"

      def install
        bin.install "substreams-sink-kv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v0.1.1/substreams-sink-kv_0.1.1_macOS_x86_64.tar.gz"
      sha256 "3ea02d04d5d4c3fceec6d171788c17b13e611a02cb1f6de4bbf2a2de914012e9"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v0.1.1/substreams-sink-kv_0.1.1_linux_x86_64.tar.gz"
      sha256 "80a2940be4036dfa295f681c4f25400d498d30bd0d30e253e61781471027a36d"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end
end
