# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkPostgres < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-postgres"
  version "2.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.0/substreams-sink-postgres_darwin_arm64.tar.gz"
      sha256 "c8b5cc6aa07402e96dbc5fb85c48e949e2d2ba5550f6696f82c30d62e37a2a4f"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.0/substreams-sink-postgres_darwin_x86_64.tar.gz"
      sha256 "791e6812636831fcde0ee8b45b45e8be3f0f7946c935d54dbce911df4c684213"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-postgres/releases/download/v2.3.0/substreams-sink-postgres_linux_x86_64.tar.gz"
      sha256 "163b5c77ebe61de35fb44326a2e80c950b160ee766a6287ec9e035c3829a839f"

      def install
        bin.install "substreams-sink-postgres"
      end
    end
  end
end
