# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkKv < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-kv"
  version "2.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.3/substreams-sink-kv_darwin_arm64.tar.gz"
      sha256 "35dec55ef7536caf015b0252be6f2311636ec38994ff58cb7d6c161c61ac4ad4"

      def install
        bin.install "substreams-sink-kv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.3/substreams-sink-kv_darwin_x86_64.tar.gz"
      sha256 "ccc73e77ce0d84d51cf73b76ccc9fc617d58e0371ebec71099734997434f4969"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-kv/releases/download/v2.1.3/substreams-sink-kv_linux_x86_64.tar.gz"
      sha256 "37434b9314d745b9ca6be0e56972af04003edefbf76d33c7271033c2fbd188b1"

      def install
        bin.install "substreams-sink-kv"
      end
    end
  end
end
