# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkNoop < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-noop"
  version "1.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-noop/releases/download/v1.1.5/substreams-sink-noop_darwin_x86_64.tar.gz"
      sha256 "4f1b19ee051b56a858663306d9d09ed6fa90f642569945b28f858d43c5fb6066"

      def install
        bin.install "substreams-sink-noop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-noop/releases/download/v1.1.5/substreams-sink-noop_darwin_arm64.tar.gz"
      sha256 "f9464a8aa4f88cb0fa434b7d07fdbe09a8ab7518efe4680ac4e6d7c65e0850cc"

      def install
        bin.install "substreams-sink-noop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-noop/releases/download/v1.1.5/substreams-sink-noop_linux_x86_64.tar.gz"
      sha256 "d96f34cdb9033b7686f3636df1d8bb0c88e62a5defddf1965bf8acb8dcc5987e"

      def install
        bin.install "substreams-sink-noop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-sink-noop/releases/download/v1.1.5/substreams-sink-noop_linux_arm64.tar.gz"
      sha256 "a13f648eb96f2d7ea7e1fdc0e07b98ca3957b696693368c55b538d85ede35e43"

      def install
        bin.install "substreams-sink-noop"
      end
    end
  end
end
