# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Substreams < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams"
  version "1.12.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams/releases/download/v1.12.4/substreams_darwin_x86_64.tar.gz"
      sha256 "c85266193eebcdc9532be21fb0637d4b8b8911f76db04b0718aee317c3c0a96c"

      def install
        bin.install "substreams"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams/releases/download/v1.12.4/substreams_darwin_arm64.tar.gz"
      sha256 "5a665f4d5d030a32e376aed5dbfeae225f4dc77a2921f1cbe48ad830992c53de"

      def install
        bin.install "substreams"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams/releases/download/v1.12.4/substreams_linux_x86_64.tar.gz"
        sha256 "33eae4ffd4a322d3c6250b681f98102bcb064cb3ad9592d1d623f1ba674d71c2"

        def install
          bin.install "substreams"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams/releases/download/v1.12.4/substreams_linux_arm64.tar.gz"
        sha256 "27410b47c3623dbdf912b71167770589d0f7668a041833f387196c9a9d78431f"

        def install
          bin.install "substreams"
        end
      end
    end
  end
end
