# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkMongodb < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-mongodb"
  version "2.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.1/substreams-sink-mongodb_darwin_arm64.tar.gz"
      sha256 "ea9fadbf9bf7a581d152760ee07ddb0b5d5df7d5e558c0cfcf83880a5fca0e5b"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.1/substreams-sink-mongodb_darwin_x86_64.tar.gz"
      sha256 "fd9a99f4de595cb15a3c8fad5eeef7ad9f5ae38b834a3e9c0683c158e1b80edc"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.1/substreams-sink-mongodb_linux_arm64.tar.gz"
      sha256 "b36226b2385d4d997eab439d83d30db29d8f29858df221f84a75a22647dde459"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-mongodb/releases/download/v2.0.1/substreams-sink-mongodb_linux_x86_64.tar.gz"
      sha256 "d52342e6b4604981ff615b43834aa6e5e76a580dc1c44110df0b310c87bf4c96"

      def install
        bin.install "substreams-sink-mongodb"
      end
    end
  end
end
