# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SubstreamsSinkFiles < Formula
  desc ""
  homepage "https://github.com/streamingfast/substreams-sink-files"
  version "2.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v2.3.1/substreams-sink-files_darwin_x86_64.tar.gz"
      sha256 "026973969c15239769eb2c996b7721fc2436c59553790face6d67b62cbf867b9"

      def install
        bin.install "substreams-sink-files"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/streamingfast/substreams-sink-files/releases/download/v2.3.1/substreams-sink-files_darwin_arm64.tar.gz"
      sha256 "253117c9f4f3a9d38b788f68f68b76d24b3207942615eac7f850da25dfeb218f"

      def install
        bin.install "substreams-sink-files"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams-sink-files/releases/download/v2.3.1/substreams-sink-files_linux_x86_64.tar.gz"
        sha256 "bea162605499bc1c225325a6b43a7a044c011a896840131a79e54988cba99ce7"

        def install
          bin.install "substreams-sink-files"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/streamingfast/substreams-sink-files/releases/download/v2.3.1/substreams-sink-files_linux_arm64.tar.gz"
        sha256 "1a3f992e210f540bc7301024e977cdc268f391c9e5f4ec7d8297e19cbdb8bb18"

        def install
          bin.install "substreams-sink-files"
        end
      end
    end
  end
end
